name:       GitHub-CI for ci-test
run-name:   Action Minimal Fail Example
on:         [push]

jobs:
  build:
    name:    "Windows 64-bit"
    rund-on: windows-latest
    defaults:
      run:
        shell:    'bash'
    env:
      MSYS: "winsymlinks:nativestrict"

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: false,
        msystem: mingw64,
        install: >-
          make
    - name: Build
      run: |
        make

