name:   Minimal Build Failure
on:     [push]
jobs:
    build:
      env:
        MSYS: "winsymlinks:nativestrict"
    defaults:
      run:
    steps:
      - name: Install build dependencies (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update:  false
          msystem: mingw64
        install: >-
          make
      - name: Run Build
        shell: bash
        run: |
          make

